Demidov alexander base64
tehnotrack/track17-autumn pull request #100
Opened 2017-10-07 22:36 UTC by DemidovAlexander

2017-10-08 16:53 UTC, tehnotrack commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +    private int toUnsignedByte(byte value) {
название метода не соответствует возвращаемому значению
тип результата операции byte_value & 0xff - Int

2017-10-08 16:53 UTC, tehnotrack commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +            int fullBitMask = toUnsignedByte(buffer[0]);
почему вы называете это маской?

2017-10-08 16:53 UTC, tehnotrack commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +                fullBitMask = fullBitMask * 256 + toUnsignedByte(buffer[i]);
Тут лучше использовать сдвиги, чем умножение.
```
val << 8
```

И почему бы не выполнить первую операцию так же в рамках внутреннего цикла?

2017-10-08 16:53 UTC, tehnotrack commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +                if (nRead < 3 && i == 0 || nRead == 1 && i == 1) {
Уверены в приоритетах операций?

2017-10-15 12:45 UTC, darkwrat requested changes

2017-10-15 12:45 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/CountWords.java
этому здесь не место

2017-10-15 12:45 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +            StringBuilder reversedResultBuilder = new StringBuilder();
зачем это нужно?

2017-10-15 16:30 UTC, DemidovAlexander commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +            StringBuilder reversedResultBuilder = new StringBuilder();
Не ясно, про что конкретно вопрос. Побитовое & нужно, чтобы корректно работать с отрицательными byte. Фактически мне хочется, чтобы в выражении значения byte были unsigned и ведущая единичка не воспринималась как минус. Кстати, когда я заливал первую версию решения, имеющиеся тесты подобные ошибки не учитывали.

StringBuilder нужен, чтобы собрать результат и записать в обратном порядке в строку. Это неправильный подход?

2017-10-15 19:23 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +            StringBuilder reversedResultBuilder = new StringBuilder();
задачу можно решить без использования стрингбилдера и сборки строки в обратном порядке. такой подход скорее вреден чем полезен -- в текущей версии потребление памяти решением будет зависеть от размера изображения, а лучше бы чтобы оно было константным

2017-10-15 20:07 UTC, darkwrat commented
принято

2017-10-15 20:07 UTC, closed without merging