Yuriyzabegaev base64
tehnotrack/track17-autumn pull request #101
Opened 2017-10-07 22:48 UTC by Yuriyzabegaev

2017-10-08 16:54 UTC, tehnotrack commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +    private static String encode(byte[] data)
почему static?

2017-10-08 16:54 UTC, tehnotrack commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +            int data3bytes = ((data[i] & 0xFF) << 16) & 0xFFFFFF; // сдвигаем 8 бит в старший байт ячейки из 3 байт
Зачем & 0xFFFFFF?

2017-10-08 16:54 UTC, tehnotrack commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +            if (i + 1 < data.length) {
Можно сделать внутренний цикл вместо 2 if-ов. И заодно упростим подсчет align

2017-10-08 16:54 UTC, tehnotrack commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +                data3bytes <<= 6; // и пошло поехало по 6 битов
Лучше обойтись без модификаций источника, код станет нагляднее

2017-10-10 16:36 UTC, darkwrat requested changes

2017-10-10 16:36 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +        String encodedStr = encode(content);
давай попробуем сделать потребление памяти энкодером константным, не зависящим от размера изображения

2017-10-10 16:36 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +            foutPath = "./result_pic";
если придет несколько запросов, они вероятно будут пытаться параллельно писать в один файл

2017-10-10 16:36 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +        outputstream.write(writeValue);
если вылетит исключение -- стримы не закроются, произойдет утечка ресурсов

2017-10-15 13:18 UTC, darkwrat requested changes

2017-10-15 13:18 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +            StringBuilder buffer = new StringBuilder();
зачем это?

2017-10-15 13:18 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +            int NumberOfBytesRead = fis.read(arrayOfBytes, 0, 3);
numberOfBytesRead если уж так

2017-10-15 13:18 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +        fos.flush();
flust неявно вызовется при close

2017-10-15 13:18 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +import java.nio.file.Paths;
где это используется?

2017-10-15 14:37 UTC, darkwrat requested changes

2017-10-15 14:37 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +        StringBuilder buffer = new StringBuilder();
вопрос тот же самый -- зачем здесь нужен стрингбилдер? имхо -- не нужен

2017-10-15 14:50 UTC, darkwrat requested changes

2017-10-15 14:50 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +    private File encode(@NotNull BufferedInputStream fis, @NotNull BufferedOutputStream fos, @NotNull int length, @NotNull String foutPath) throws IOException {
давай не будем здесь использовать length, а читать из стрима до конца

2017-10-15 14:50 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +                    final BufferedOutputStream fos = new BufferedOutputStream(new FileOutputStream(fout));
предлагаю сделать тип переменной InputStream или OutputStream, чтобы зависить от абстракции а не от реализации

2017-10-15 14:50 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +                return retValue;
а почему не сказать сразу return encode?

2017-10-15 14:50 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +        return new File(foutPath);
а для чего мы передаем файл в эту функцию, ничего с ним не делаем а затем возвращаем?

2017-10-15 14:50 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +            final File fin = new File(finPath);
почему здесь разный отступ? автоформатирование применял?

2017-10-15 15:27 UTC, darkwrat commented
принял

2017-10-15 15:27 UTC, closed without merging