Kuskovars base64
tehnotrack/track17-autumn pull request #107
Opened 2017-10-10 21:30 UTC by kuskovars

Понял, что не нужно было мерджить другие задания в свой мастер, чтобы можно было сдавать только одно задание. 
Но для этого пришлось удалить и заного залить репозиторий, теперь там куча коммитов снизу. От этого можно как-то избавиться?

2017-10-11 17:37 UTC, darkwrat commented
git rebase -i

2017-10-15 13:14 UTC, darkwrat requested changes

2017-10-15 13:14 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +        final BufferedOutputStream ofStream = new BufferedOutputStream(new FileOutputStream(fout));
try-with-resources

2017-10-15 13:14 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +                ifStream.read(data, 0, 3);
read() возвращает значение. может быть если его использовать -- код упростится?

2017-10-15 13:14 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +        ofStream.flush();
flush при close вызывается неявно, это не нужно

2017-10-15 13:14 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +        ofStream.close();
если какой-то из write кинет IOException -- произойдет утечка ресурсов. смотри в сторону try-with-resources

2017-10-17 18:41 UTC, kuskovars commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +        final BufferedOutputStream ofStream = new BufferedOutputStream(new FileOutputStream(fout));
Fixed.

2017-10-17 18:41 UTC, kuskovars commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +                ifStream.read(data, 0, 3);
И правда ;)

2017-10-17 18:41 UTC, kuskovars commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +        ofStream.flush();
Fixed.

2017-10-17 18:42 UTC, kuskovars commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +        ofStream.close();
Прикольно, когда на такие тонкости указывают. 
Исправил.

2017-10-17 19:46 UTC, darkwrat approved these changes

2017-10-17 19:48 UTC, darkwrat commented
принял. хотя .available() можно не вызывать, тупо проверять что read вернул норм число

2017-10-17 19:48 UTC, closed without merging