Semjon base64
tehnotrack/track17-autumn pull request #129
Opened 2017-10-14 19:30 UTC by Senbjorn

Improved solution

2017-10-15 12:30 UTC, darkwrat commented
зачем это здесь? если вы не хотите получить половину баллов за эту задачу -- обновите старый пуллреквест

2017-10-15 13:42 UTC, darkwrat commented
https://github.com/tehnotrack/track17-autumn/pull/72

2017-10-15 17:12 UTC, darkwrat requested changes

2017-10-15 17:12 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +        } catch (FileNotFoundException e) {
это нужно выпилить -- ничего вменяемого в этом catch-блоке не происходит

2017-10-15 17:12 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +        } catch (IOException e) {
это нужно выпилить -- метод задекларирован как throws IOException

2017-10-15 17:12 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +        } finally {
такой блок finally проглотит исключение -- он просто здесь не нужен

2017-10-15 17:12 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +            StringBuilder encoded = new StringBuilder(); // string to put into fout
зачем здесь это? можно сразу писать на выход, а не тратить память попусту

2017-10-15 17:12 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +        File fout; // file with encoded data to be returned
комменты здесь не нужны -- над методом есть документация

2017-10-18 20:59 UTC, Senbjorn commented
Понял про комменты забыл их удалить. Там убрал строки сразу в файл пишу. И идиотский файналли убрал.

2017-10-20 14:07 UTC, Senbjorn commented
Я все что нужно сделал теперь

2017-10-21 22:02 UTC, darkwrat commented
принято

2017-10-21 22:02 UTC, closed without merging