andpago-base64
tehnotrack/track17-autumn pull request #158
Opened 2017-10-22 11:06 UTC by vestatus

2017-10-22 11:11 UTC, tehnotrack commented
А зачем новы реквест? От вас же был уже https://github.com/tehnotrack/track17-autumn/pull/35

2017-10-22 11:13 UTC, andpago commented
Я накосячил с ветками там, а вычистить всё так, чтобы остались только нужные файлы, у меня не получилось. Тот реквест я закрыл

2017-10-22 13:39 UTC, darkwrat requested changes

2017-10-22 13:39 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +        InputStream inputStream = new FileInputStream(finPath);
из-за отсутствия буферизации ввода-вывода такого решение ушатает всю систему по системным вызовам при сколько-то вменяемой нагрузке -- машина просто встанет в 100% sys cpu

2017-10-22 13:39 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +        while(inputStream.available() > 2) {
.read() возвращает значение -- предлагаю использовать его

2017-10-22 13:39 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +            chunkValue =inputStream.read() * 65536 +
давай использовать битовые сдвиги

2017-10-22 13:39 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +        inputStream.close();
если какой write упадет с IOException -- ресурсы не закроются. нужно использовать возможности AutoClosable с помощью try-with-resources

2017-10-27 09:02 UTC, darkwrat approved these changes

2017-10-27 09:03 UTC, darkwrat commented
принято

2017-10-27 09:03 UTC, closed without merging