Andpago base64
tehnotrack/track17-autumn pull request #35
Opened 2017-09-27 12:12 UTC by andpago

2017-09-28 09:45 UTC, darkwrat commented
оставь, пожалуйста, в мердже только те файлы которые нужны для того чтобы решение работало.
обычно в проекте есть настроенный .gitignore, но даже если его нет -- апстриму как правило не нужны настройки твоей ide, у каждого разработчика они свои.

2017-09-28 09:56 UTC, darkwrat requested changes

2017-09-28 09:56 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +        // throw new UnsupportedOperationException(); // TODO: implement
давай уберем этот коммент -- решение уже реализовано ;)

2017-09-28 09:56 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +        StringBuilder builder = new StringBuilder();
обычно для переменных на стеке, которые не будут переопределяться, ставят модификатор final

2017-09-28 09:56 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +        Files.write(fout.toPath(), res.getBytes());
если в твой сервер придёт N запросов -- то он съест 2 * X * N памяти, где X -- размер картинки,
то есть отожрёт гигабайт при сотне одновременных запросов за картинкой в 5 мегабайт.
есть идеи как оптимизировать?))

2017-09-28 09:56 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +            System.out.println(res.substring(i * L, i * L + L));
убери, пожалуйста, отладочные выводы

2017-09-28 10:35 UTC, andpago commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +        Files.write(fout.toPath(), res.getBytes());
теперь оно запоминает, какие файлы уже закодированы, и отдаёт их, а не считает base64 каждый раз

2017-09-28 13:19 UTC, darkwrat requested changes

2017-09-28 13:19 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +        final byte[] data = Files.readAllBytes(Paths.get(finPath));
всё-таки лучше не читать целиком файл в память, а использовать InputStream/OutputStream

2017-09-28 13:19 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +    private int convertToUnsigned(byte k) {
static

2017-09-28 13:19 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +import java.util.HashSet;
не нужно

2017-09-28 13:19 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +    private HashMap<String, String> encodedFiles = new HashMap<>(); // maps input to output fnames
если encodeFile будет дергаться из нескольких потоков (что вероятнее всего при обслуживании множества запросов) -- здесь возникнет race condition.

2017-09-28 13:19 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +        String res = builder.toString();
final

2017-09-28 13:19 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +        encodedFiles.put(finPath, fout.getPath());
.getCanonicalPath() тогда уж, и на get тоже

2017-09-28 13:19 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +        k = 65536;
мне кажется использовать битовые сдвиги более логично

2017-09-28 13:19 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +        Files.write(fout.toPath(), res.getBytes());
неплохая идея, но я считаю что кешированием должен заниматься вызывающий код, и это не работа энкодера.
я предлагаю использовать возможности, которые дают InputStream и OutputStream -- читать по три байта из входного потока, разбираться с ними, писать в выходной и забывать про них. тогда потребление памяти твоей штукой будет константное

2017-10-08 11:36 UTC, darkwrat commented
нужно отсюда убрать изменения, которые не относятся к задаче

2017-10-15 12:40 UTC, darkwrat commented
{code}
[ERROR] Failures: 
[ERROR]   FileEncoderTest.testEncoderImplementation:72 expected:<2P/g/[w]==> but was:<2P/g/[=]==>
[ERROR]   FileEncoderTest.testEncoderImplementation:72 expected:</9j/4[A]==> but was:</9j/4[=]==>
[ERROR]   FileEncoderTest.testEncoderImplementation:72 expected:<eH[g]=> but was:<eH[=]=>
[ERROR]   FileEncoderTest.testEncoderImplementation:72 expected:<e[A]==> but was:<e[=]==>
[ERROR]   FileEncoderTest.testEncoderImplementation:72 expected:<eHh4MD[A]=> but was:<eHh4MD[=]=>
[ERROR]   FileEncoderTest.testEncoderImplementation:72 expected:<eHh4M[A]==> but was:<eHh4M[=]==>
[ERROR]   FileEncoderTest.testEncoderImplementation:77 files differ at byte 5463
[ERROR]   FileEncoderTest.testEncoderImplementation:77 files differ at byte 5466
[INFO] 
[ERROR] Tests run: 15, Failures: 8, Errors: 0, Skipped: 1
{code}

2017-10-15 12:41 UTC, darkwrat approved these changes

2017-10-21 22:07 UTC, darkwrat commented
здесь что-то будет?

2017-10-22 11:07 UTC, vestatus commented
Перенёс сюда:
https://github.com/tehnotrack/track17-autumn/pull/158

2017-10-22 11:11 UTC, closed without merging