materkey-base64
tehnotrack/track17-autumn pull request #36
Opened 2017-09-27 22:52 UTC by materkey

2017-09-28 09:59 UTC, darkwrat commented
спасибо что нет лишних файлов :thumbsup:

2017-09-28 10:06 UTC, darkwrat requested changes

2017-09-28 10:06 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +    @Contract("_, _ -> fail")
кажется, контракт устарел когда появилась реализация

2017-09-28 10:06 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +            byte[] input = IOUtils.toByteArray(fis);
может быть можно обойтись без кеширования входного файла в памяти программы?
если придёт много запросов -- сервер ляжет по памяти

2017-09-28 10:06 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +            StringBuilder output = new StringBuilder();
обычно локальные переменные-ссылки делают final

2017-09-28 10:06 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +            StringBuilder output = new StringBuilder();
здесь такая же схема как с входным буфером -- может быть можно без него обойтись?
рекомендую посмотреть как устроен IOUtils.copy

2017-09-28 20:37 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +    private static class Base64OutputStream extends FilterOutputStream {
если делать так -- то можно и public class в отдельном файле.
а вообще наверное можно обойтись без своей реализации если сделать входной и выходной buffered и юзать прямо .read() и .write() для байтов

2017-09-28 20:37 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +                out.write('=');
вот тут возможно будет баг. IOUtils.copy() внутри использует буфер размером 4096 байт, что на 3 не делится. и тогда на каждый write может появляться паддинг в выходных данных. пока не понял, запрещает это RFC 4648 или нет, но данных может получиться на выходе больше чем нужно. если напишешь тест на такой случай -- вообще прекрасно будет.

2017-09-29 14:43 UTC, materkey commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +                out.write('=');
сделал

2017-09-29 17:36 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +        final int bufSize = 3000;
давай попробуем избавиться от этого тайного знания
а что если здесь буферизовать <= 3 байт?

2017-09-29 19:44 UTC, materkey commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +        final int bufSize = 3000;
под меньше 3х алгоритм не заточен, сделал 3 байтаи переименовал в base64InputLength. это решает проблему тайного знания?

2017-10-02 05:46 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +        final int bufSize = 3000;
то что алгоритм не заточен -- это понятно. речь о том что размер буфера 3 байта и он бывает недозаполнен.
я имел в виду тайное знание о том что поведение функции base64Write может *внезапно* изменяться в зависимости от длины блока. здесь более или менее умный компилятор должен заинлайнить её в место вызова и избавиться от пары условий.
если сделать такое же преобразование руками -- будет меньше кода, ведь никто не любит код :)
заодно можно и от трехбайтного буфера избавиться (вспомни ObjectLayoutDemo - какой оверхед на них) -- просто вычитывать условные примитивные byte a,b,c с помощью fis.read()

2017-10-03 08:08 UTC, tehnotrack commented
я мучаю ваш пр на билд системе. Могут приходить письма

2017-10-08 11:35 UTC, darkwrat approved these changes

2017-10-09 19:31 UTC, materkey commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +        final int bufSize = 3000;
заинлайнил и избавился от трехбайтного буфера

2017-10-09 21:23 UTC, darkwrat commented
а можешь запилить отдельный пуллреквест с тестом? я его замерджу
кст может быть неплохо его чуть причесать, что там гугл говорит насчёт умножения строк в джаве

2017-10-15 11:57 UTC, darkwrat commented
принял

2017-10-15 11:57 UTC, closed without merging