Rudenko Nikita
tehnotrack/track17-autumn pull request #41
Opened 2017-10-01 12:40 UTC by nLoro

2017-10-02 06:07 UTC, darkwrat commented
тесты упадут )

2017-10-02 07:37 UTC, nLoro commented
А почему? Т.е. в логике энкодера ошибка?

2017-10-02 21:05 UTC, darkwrat commented on L2-objects/out.txt
> +iVBORw0KGgoAAAANSUhEUgAAAQAAAAEACAYAAABccqhmAAAACXBIWXMAAAsTAAALEwEAmpwYAAAKT2lDQ1BQaG90b3Nob3AgSUNDIHByb2ZpbGUAAHjanVNnVFPpFj333vRCS4iAlEtvUhUIIFJCi4AUkSYqIQkQSoghodkVUcERRUUEG8igiAOOjoCMFVEsDIoK2Af
DeAD
DiCK
TOYs
RUsICQ

выпили плз )

2017-10-02 21:05 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +    private int toUnsigned(byte[] buffer)
static

2017-10-02 21:05 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +                os.write(toBase64[index]);
test it!

2017-10-02 21:05 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/vendor/ReferenceTaskImplementation.java
> -        if (foutPath != null) {
git checkout L2-objects/src/main/java/ru/track/io/vendor/ReferenceTaskImplementation.java

2017-10-02 21:05 UTC, darkwrat commented on L2-objects/src/test/java/ru/track/io/vendor/FileEncoderTest.java
> +
git checkout  L2-objects/src/test/java/ru/track/io/vendor/FileEncoderTest.java

2017-10-02 22:40 UTC, nLoro commented on L2-objects/out.txt
> +iVBORw0KGgoAAAANSUhEUgAAAQAAAAEACAYAAABccqhmAAAACXBIWXMAAAsTAAALEwEAmpwYAAAKT2lDQ1BQaG90b3Nob3AgSUNDIHByb2ZpbGUAAHjanVNnVFPpFj333vRCS4iAlEtvUhUIIFJCi4AUkSYqIQkQSoghodkVUcERRUUEG8igiAOOjoCMFVEsDIoK2Af
Убрал. Но не понял что это...

2017-10-02 22:43 UTC, nLoro commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +                os.write(toBase64[index]);
В браузере все работает. Тесты запустить не смог.
![1](https://user-images.githubusercontent.com/28059451/31102763-3c3e17c4-a7dc-11e7-9e2e-be1746e298b6.PNG)
![2](https://user-images.githubusercontent.com/28059451/31102762-3c3867d4-a7dc-11e7-9408-f97358051f13.PNG)

2017-10-03 10:20 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +                os.write(toBase64[index]);
а если просто сказать mvn test в папке L2?

2017-10-03 22:31 UTC, nLoro commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +                os.write(toBase64[index]);
команда mvn test сработала)

2017-10-03 23:19 UTC, nLoro commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +                os.write(toBase64[index]);
Исправил ошибки,
mvn test работает, а
mvn -Dtest=\!CountWordsTest clean install  - не работает.
![1](https://user-images.githubusercontent.com/28059451/31153404-ba263630-a8a9-11e7-8ffb-eab07ecaf706.PNG)
И на семафоре перестал билдится...

2017-10-04 11:26 UTC, tehnotrack commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +                os.write(toBase64[index]);
Вытяни апстрим плиз, я поднял версию мавен плагина
maven-surefire-plugin:2.12.4

нужнен новый код с L2-objects&
как вытянешь и смерджишь со своим - снова комитни

2017-10-04 17:01 UTC, nLoro commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +                os.write(toBase64[index]);
Сделал, заработало

2017-10-15 13:22 UTC, darkwrat requested changes
1. нужно выпилить лишнее
2. нужно применить автоформатирование кода
3. нужно поправить комменты

2017-10-15 13:22 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +        OutputStream os = new FileOutputStream(fout);
try-with-resources

2017-10-15 13:22 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +        OutputStream os = new FileOutputStream(fout);
нужна буферизация

2017-10-15 15:19 UTC, nLoro commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +        OutputStream os = new FileOutputStream(fout);
1. Лишнее это та картиночка? Убрал
2. Наверное вы имеете ввиду автоформатирование по-умолчанию? Так то с форматированием все хорошо. Исправил.
3. Поправил.

2017-10-15 15:24 UTC, nLoro commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +        OutputStream os = new FileOutputStream(fout);
Иии... оно не проходит. Игнорировать?
![capture](https://user-images.githubusercontent.com/28059451/31586162-0e0371f2-b1d6-11e7-9741-a7d5bb03f627.PNG)

2017-10-15 15:31 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +            fos.close();
зачем здесь это? глянь плз как работает try-with-resources

2017-10-15 15:31 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +        OutputStream os = new FileOutputStream(fout);
если запускать локально, всё проходит
```
[INFO] Tests run: 14, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.386 s - in ru.track.io.vendor.FileEncoderTest
```

2017-10-15 15:37 UTC, nLoro commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +        OutputStream os = new FileOutputStream(fout);
Локально - да.
Принято?

2017-10-15 15:44 UTC, nLoro commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +            fos.close();
Тип закрывает ресурсы автоматически? Убрал.

2017-10-15 15:55 UTC, darkwrat commented
принял

2017-10-15 15:55 UTC, closed without merging