Manwithhonor base64
tehnotrack/track17-autumn pull request #44
Opened 2017-10-02 11:06 UTC by manwithhonor

Completed second hometask

2017-10-07 14:09 UTC, darkwrat commented
выпили пожалуйста лишние файлы

2017-10-07 17:33 UTC, manwithhonor commented
finaly!
it's working

2017-10-07 17:42 UTC, darkwrat commented on L2-objects/pom.xml
>                  <groupId>org.apache.maven.plugins</groupId>
git checkout upstream/master L2-objects/pom.xml

2017-10-07 17:42 UTC, darkwrat commented on L2-objects/L2.iml
> +</module>
git rm --cached L2-objects/L2.iml

2017-10-07 17:42 UTC, darkwrat commented on L1-intro/src/test/java/ru/track/AppTest.java
> -}
git checkout upstream/master L1-intro/src/test/java/ru/track/AppTest.java

2017-10-07 17:42 UTC, darkwrat commented on L1-intro/src/main/java/ru/track/App2.java
> -}
git checkout upstream/master  L1-intro/src/main/java/ru/track/App2.java

2017-10-07 17:42 UTC, darkwrat commented on L1-intro/src/main/java/ru/track/App.java
> -}
git checkout upstream/master  L1-intro/src/main/java/ru/track/App.java

2017-10-07 17:42 UTC, darkwrat commented on L1-intro/pom.xml
> -</project>
git checkout upstream/master  L1-intro/pom.xml

2017-10-07 17:42 UTC, darkwrat commented on L1-intro/OWNER.md
> -Dmitry Arkhangelskiy
git checkout upstream/master L1-intro/OWNER.md

2017-10-07 18:27 UTC, manwithhonor commented on L1-intro/OWNER.md
> -Dmitry Arkhangelskiy
это вторая домашка, и Вы мне сами сказали убрать все лишние файлы и папки.

данная команда возвращает во вторую домашку папку L1.

Зачем?

2017-10-09 10:57 UTC, tehnotrack commented on L1-intro/OWNER.md
> -Dmitry Arkhangelskiy
Лишние - это те, которые не относятся к проекту. В данном случае L1 - это часть проекта и он лежит в репозитории, поэтому удалять то, что уже лежит в апстрим репозитории не нужно. Это снова делает пулл-реквест сложночитаемым

2017-10-09 11:52 UTC, darkwrat commented on L1-intro/OWNER.md
> -Dmitry Arkhangelskiy
отвечал в личку. нужно убирать не лишние файлы, а лишние изменения. чтобы в мерджреквесте было только то что нужно для задачи.

2017-10-25 04:47 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +        BufferedInputStream input = new BufferedInputStream(new FileInputStream(fin));
стримы за собой надо закрывать. желательно использовать возможности AutoClosable

2017-10-25 04:47 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +            out.write(new String(result).getBytes());
если не секрет -- зачем здесь создается строка?

2017-10-29 12:34 UTC, manwithhonor commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +            out.write(new String(result).getBytes());
на вход write  нужно подать byte
а result у меня char

на вопрос как перевести char to byte, я нашел слдующее решение 
https://stackoverflow.com/questions/5513144/converting-char-to-byte

это неправильно? мне исправить?

2017-11-08 09:55 UTC, darkwrat requested changes

2017-11-08 09:55 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +public final class TaskImplementation implements FileEncoder, AutoCloseable {
так это не работает. необходимо разобраться что это такое.

2026-04-15 12:10 UTC, closed without merging