1task
tehnotrack/track17-autumn pull request #54
Opened 2017-10-04 17:22 UTC by Cheshear

2017-10-07 22:24 UTC, darkwrat commented
чьё это? почему здесь так много лишних изменений?

2017-10-08 19:28 UTC, Cheshear commented
Попова Мария

2017-10-08 19:28 UTC, Cheshear commented
я же вроде создала .gitignore файлик

2017-10-08 21:20 UTC, darkwrat commented
договорились что до вторника надо оформить мердж нормально

2017-10-09 16:44 UTC, darkwrat requested changes

2017-10-09 16:44 UTC, darkwrat commented on L1-intro/src/main/java/ru/track/App.java
> -}
git checkout upstream/master L1-intro/src/main/java/ru/track/App.java

2017-10-09 16:44 UTC, darkwrat commented on L1-intro/src/main/java/ru/track/App2.java
> -}
git checkout upstream/master L1-intro/src/main/java/ru/track/App2.java

2017-10-09 16:44 UTC, darkwrat commented on L1-intro/src/test/java/ru/track/AppTest.java
> +import jdk.nashorn.internal.ir.annotations.Ignore;
?

2017-10-09 16:44 UTC, darkwrat commented on L1-intro/src/test/java/ru/track/AppTest.java
> +@Ignore
?

2017-10-09 17:16 UTC, darkwrat approved these changes

2017-10-09 17:16 UTC, darkwrat commented
принято

2017-10-09 17:16 UTC, closed without merging