Bukin Kirill base64
tehnotrack/track17-autumn pull request #65
Opened 2017-10-04 21:02 UTC by BKirill

2017-10-07 14:05 UTC, darkwrat commented
выпили пожалуйста лишние файлы

2017-10-09 08:56 UTC, BKirill commented
Убрал лишнее

2017-10-09 12:05 UTC, darkwrat requested changes

2017-10-09 12:05 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +            strb.append(out);
а зачем здесь нужен strb? почему нельзя сразу os.write?

2017-10-09 12:05 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +        FileOutputStream os = new FileOutputStream(fout);
стримы кто-то должен закрыть. лучше всего использовать try-with-resources

2017-10-09 12:05 UTC, darkwrat commented
из-за отсутствия буферизации уведешь тачку в полку по %sy
```
m.galaganov@ntco6 ~ % strace -f -e trace=read,write -p4514 -o trace.log
Process 4514 attached with 24 threads
.....
4542  read(104, "\340\0\20", 3)         = 3
4542  write(105, "4", 1)                = 1
4542  write(105, "A", 1)                = 1
4542  write(105, "A", 1)                = 1
4542  write(105, "Q", 1)                = 1
4542  read(104, "JFI", 3)               = 3
4542  write(105, "S", 1)                = 1
4542  write(105, "k", 1)                = 1
4542  write(105, "Z", 1)                = 1
4542  write(105, "J", 1)                = 1
4542  read(104, "F\0\1", 3)             = 3
4542  write(105, "R", 1)                = 1
4542  write(105, "g", 1)                = 1
4542  write(105, "A", 1)                = 1
4542  write(105, "B", 1)                = 1
4542  read(104, "\1\0\0", 3)            = 3
4542  write(105, "A", 1)                = 1
4542  write(105, "Q", 1)                = 1
4542  write(105, "A", 1)                = 1
4542  write(105, "A", 1)                = 1
4542  read(104, "\1\0\1", 3)            = 3
4542  write(105, "A", 1)                = 1
4542  write(105, "Q", 1)                = 1
4542  write(105, "A", 1)                = 1
4542  write(105, "B", 1)                = 1
.....
```

2017-10-10 20:23 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +            BufferedOutputStream bos = new BufferedOutputStream(os)){
new BufferedOutputStream(new FileOutputStream(fout))

2017-10-10 20:23 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +                bos.write(new String(out).getBytes("UTF-8"));
зачем new String() ?

2017-10-15 12:27 UTC, darkwrat approved these changes

2017-10-15 12:28 UTC, darkwrat commented
принял

2017-10-15 12:28 UTC, closed without merging