Simple http-client
tehnotrack/track17-autumn pull request #74
Opened 2017-10-05 13:57 UTC by NifantovaIrina

2017-10-07 12:35 UTC, darkwrat requested changes

2017-10-07 12:35 UTC, darkwrat commented on httpClient/src/main/java/ru/track/myHttpClient.java
> +class MyHttpClient {
имя класса не совпадает с именем файла. так нельзя.

2017-10-08 11:34 UTC, darkwrat approved these changes

2017-10-08 16:57 UTC, tehnotrack commented
принято

2017-10-08 16:57 UTC, closed without merging