Vasili4396 base64
tehnotrack/track17-autumn pull request #88
Opened 2017-10-06 21:55 UTC by vasili4396

2017-10-07 13:59 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +import javafx.util.converter.IntegerStringConverter;
O_o

2017-10-07 13:59 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +                    System.out.println(c);
нет

2017-10-07 13:59 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +                            sb.append ("00000000");
?

2017-10-07 13:59 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +                        arr[j] = Integer.parseInt(sb.substring(6 * j, 6 * (j + 1)), 2);
сложнооооо

2017-10-07 13:59 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +        //throw new UnsupportedOperationException(); // TODO: implement
выпили плз

2017-10-07 13:59 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +            StringBuilder sb = new StringBuilder();
давай не будем буферизовать выходные данные, чтобы не тратить память попусту

2017-10-07 15:14 UTC, vasili4396 commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +import javafx.util.converter.IntegerStringConverter;
исправил. видимо, intellij idea сама подгрузила их

2017-10-07 15:14 UTC, vasili4396 commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +            StringBuilder sb = new StringBuilder();
так я вроде сразу как только перевожу, записываю в файл, ничего не буферизуя.

for (int j = 0; j < 4; j++) {
                        arr[j] = Integer.parseInt(sb.substring(6 * j, 6 * (j + 1)), 2);
                        fout1.print(toBase64[arr[j]]);
                    }

2017-10-07 15:15 UTC, vasili4396 commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +                    System.out.println(c);
если это к System.out.println, то исправил.

2017-10-07 15:19 UTC, vasili4396 commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +                            sb.append ("00000000");
отдельно обрабатываю случай когда в конце записался 1(2) байта из 3. если записался только 1 байт, дописываю в конец 2*8 нулей, если 2 байта - 8 нулей.

2017-10-07 15:23 UTC, vasili4396 commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +                        arr[j] = Integer.parseInt(sb.substring(6 * j, 6 * (j + 1)), 2);
в sb хранится целиком строку из 24 бит. есть массив arr[4] в который загоняю результат перевода (4 числа по 6 бит).

2017-10-07 17:16 UTC, vasili4396 reviewed
вроде поправил что было

2017-10-10 21:35 UTC, vasili4396 reviewed
посмотрел какие еще варианты есть, но там все основано на работе с побитовыми операциями. у меня же алгоритм построен на том, что я играюсь со строкой. немного не знаю как это исправить

2017-10-11 13:23 UTC, vasili4396 reviewed
Переделано.

2017-10-15 12:49 UTC, darkwrat requested changes

2017-10-15 12:49 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +            //upd:13.10.17 надеюсь теперь тесты будут проходить.
надо не надеяться а запускать их руками

2017-10-15 12:49 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +            // -------ниже старая версия кода, рабочая, но там все муторно и построено все на работе со строками
зачем это здесь?

2017-10-15 12:49 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +            BufferedOutputStream fout1 = new BufferedOutputStream(new FileOutputStream(fout)); //стрим для записи в файл
try-with-resources

2017-10-15 12:49 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +            BufferedOutputStream fout1 = new BufferedOutputStream(new FileOutputStream(fout)); //стрим для записи в файл
комментарий не нужен -- он абсолютно бесполезен

2017-10-15 12:49 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +            int num_of_bytes_read, num;
нет. в java используется camelCase а не snake_case

2017-10-15 14:36 UTC, darkwrat commented
принял

2017-10-15 14:36 UTC, closed without merging