Akimowkirill base64
tehnotrack/track17-autumn pull request #90
Opened 2017-10-07 00:13 UTC by AtlasKirill

2017-10-07 13:55 UTC, darkwrat commented
прошу выпилить лишние изменения

2017-10-07 15:35 UTC, AtlasKirill commented
Я пробовал делать rm ненужных файлов, они все равно остаются. Добавлять их в gitignore - и все по-прежнему. Подскажите, как мне их убрать

2017-10-07 15:38 UTC, darkwrat commented
git checkout upstream/master _файл_

2017-10-07 15:59 UTC, AtlasKirill commented
Теперь все ок?

2017-10-07 17:34 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +        //throw new UnsupportedOperationException(); // TODO: implement
давай выпилим этот коммент

2017-10-07 17:34 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +        File out_file;
в java обычно используют camelCase а не snake_case

2017-10-07 17:34 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +        } catch (IOException e) {
давай выпилим catch совсем

2017-10-07 17:34 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +        StringBuilder data = new StringBuilder();
зачем буферизовать входной файл в памяти? если прилетит много запросов -- сервер упадет с out-of-memory

2017-10-07 17:34 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +                r += "\r\n";
какие \r\n, мы не реализуем mime-кодирование, нам они не нужны. копипаст откуда?

2017-10-07 17:34 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +        pw.write(r.substring(0, r.length() - p.length()) + p);
https://docs.oracle.com/javase/8/docs/api/java/io/PrintWriter.html
эта штука потиху съест IOException, не надо так

2017-10-09 13:37 UTC, AtlasKirill commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +        File out_file;
ну прошлое С++ нельзя вот взять и перечеркнуть)

2017-10-09 15:13 UTC, AtlasKirill commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +        StringBuilder data = new StringBuilder();
а как связана буферизация файла с StringBuilder?

2017-10-09 15:40 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +        StringBuilder data = new StringBuilder();
логично что StringBuilder внутри хранит буфер в который доливают то что в него аппендят. ну вот и получается что потребление памяти зависит от размера картинки, а хотелось бы от этого уйти

2017-10-09 15:40 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +        File out_file;
не аргумент, в рамках этого курса мы пишем на Java

2017-10-09 15:43 UTC, AtlasKirill commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +        StringBuilder data = new StringBuilder();
так мы же должны прочитать ее полностью, то есть мы по умолчанию зависим от ее размера, разве не так?

2017-10-09 15:45 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +        StringBuilder data = new StringBuilder();
а почему мы должны прочитать её полностью сразу в память? откуда взялось такое ограничение?

2017-10-09 15:53 UTC, AtlasKirill commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +        StringBuilder data = new StringBuilder();
а, вы имеете в виду, что можно прочитать ее по байтам в байтовый массив, к примеру?

2017-10-09 15:56 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +        StringBuilder data = new StringBuilder();
да хоть как, главное не всю сразу. давай есть слона по частям.

2017-10-09 16:09 UTC, AtlasKirill commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +        StringBuilder data = new StringBuilder();
так подождите, я читаю файл через BufferedReader ниже, а уже из него вытягиваю массив символов в StringBuilder

2017-10-09 16:10 UTC, AtlasKirill commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +        StringBuilder data = new StringBuilder();
Я читаю его по кусочкам

2017-10-09 16:12 UTC, AtlasKirill commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +        StringBuilder data = new StringBuilder();
или BufferedReader работает по-другому?

2017-10-09 16:12 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +        StringBuilder data = new StringBuilder();
оцени пожалуйста сложность твоего энкодера по памяти

2017-10-09 16:20 UTC, AtlasKirill commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +        StringBuilder data = new StringBuilder();
то есть сколько памяти потребуется программе?
насколько я понимаю, 3n ,где n - это размер картинки

2017-10-09 16:24 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +        StringBuilder data = new StringBuilder();
давай попробуем сделать так чтобы ему требовалось X байт памяти, где X -- это константа

2017-10-09 16:27 UTC, AtlasKirill commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +        StringBuilder data = new StringBuilder();
а X==размер картинки?

2017-10-09 16:27 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +        StringBuilder data = new StringBuilder();
нет, тогда это не константа

2017-10-09 17:31 UTC, AtlasKirill commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +        StringBuilder data = new StringBuilder();
а если читать по три байта, нормально?

2017-10-09 17:42 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +        StringBuilder data = new StringBuilder();
главное чтобы от этого тачка не усосала по сисколлам

2017-10-09 20:46 UTC, AtlasKirill commented
Теперь все правильно?

2017-10-09 21:15 UTC, darkwrat requested changes
![default](https://user-images.githubusercontent.com/1160968/31358848-64a2326e-ad58-11e7-9c5f-c6065972ed8e.png)
у меня картинка не показывается, чяднт?
нужно разобраться и добавить в тесты

2017-10-09 21:15 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +                    r += "" + toBase64[n1] + toBase64[n2]
контатенация строк в цикле -- не самая лучшая идея, разбирались с ней первом занятии

2017-10-09 21:33 UTC, AtlasKirill commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +                    r += "" + toBase64[n1] + toBase64[n2]
А, ок. Не могу найти ссылку на видео, где мы это разбирали. Может вкратце напомните?

2017-10-09 21:39 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +                    r += "" + toBase64[n1] + toBase64[n2]
это L2 таки, была задачка CountWords -- идея в том что порождается очень мног мелких объектов, потому что строки неизменяемы. там рекомендуется использовать StringBuilder, в этой задаче можно без него обойтись

2017-10-09 21:57 UTC, AtlasKirill commented
Она также не отображает картинку
Не подскажете, где искать ошибку, ибо тесты все проходят

2017-10-09 22:25 UTC, darkwrat commented
попробуй применить через git apply такой патч, а потом поменять путь к картинке -- и смотри на выхлоп тестов
https://gist.github.com/darkwrat/cd9f18d4011f2d7a45acd4d4e6e16c2a

2017-10-09 22:39 UTC, AtlasKirill commented
Нашел в чем была ошибка: в побитовом сдвиге не додвигал на 2 знака

2017-10-09 22:40 UTC, AtlasKirill commented
Теперь кот появляется

2017-10-09 22:40 UTC, darkwrat commented
напиши плз тест на это и сделай отдельным пуллреквестом, я приму

2017-10-09 22:44 UTC, AtlasKirill commented
так, а можно теперь про тест поподробнее? дополнить FileEncoderTest? что он должен проверять?

2017-10-09 23:08 UTC, darkwrat commented
тут хитро -- ты напоролся на хедер jpeg, а он -- сурогатная пара. я сейчас запушу тесты, вмерджи плз мастер

2017-10-09 23:29 UTC, AtlasKirill commented
да, тест появился, только что от меня требуется?

2017-10-09 23:34 UTC, darkwrat commented
git merge upstream/master
git push origin AtlasKirill:akimowkirill-base64

2017-10-09 23:41 UTC, darkwrat approved these changes

2017-10-09 23:45 UTC, AtlasKirill commented
теперь все ок?

2017-10-09 23:48 UTC, darkwrat commented
ок если пройдут новые тесты. для  этого их надо вмерджить и запушить

2017-10-11 20:11 UTC, AtlasKirill commented
reformat code - удалить лишние файлы из комитов?

2017-10-11 20:18 UTC, darkwrat commented
нет
https://www.jetbrains.com/help/idea/reformatting-source-code.html

2017-10-15 12:03 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +                    for(int i=0;i<4;i++){
нужно разобраться как применять автоматическое форматирование исходного кода в идее

2017-10-15 12:04 UTC, darkwrat commented
принято

2017-10-15 12:04 UTC, closed without merging