PeYceBall-base64
tehnotrack/track17-autumn pull request #96
Opened 2017-10-07 15:54 UTC by PeYceBall

Илья Воробьёв. 
Оставил в коммите только java файлы

2017-10-07 17:04 UTC, darkwrat reviewed
а где старый pull request? переоткрывать их не нужно

2017-10-07 17:04 UTC, darkwrat commented on OWNER.md
> +������� ���� ����������
нечитаемо (

2017-10-07 17:04 UTC, darkwrat commented on L2-objects/src/test/java/ru/track/CountWordsTest.java
> -}
git checkout upstream/master L2-objects/src/test/java/ru/track/CountWordsTest.java

2017-10-07 17:04 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/CountWords.java
> -
git checkout upstream/master L2-objects/src/main/java/ru/track/CountWords.java

2017-10-07 17:04 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +}
нужно сделать автоматическое переформатирование кода

2017-10-15 13:05 UTC, darkwrat requested changes

2017-10-15 13:05 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +            StringBuilder sb = new StringBuilder();
но зачем?

2017-10-15 13:05 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +                    } catch (ArrayIndexOutOfBoundsException e) {
???

2017-10-15 13:05 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +        } catch (IOException e) {
???

2017-10-15 13:05 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +        try {
???

2017-10-15 13:05 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +            FileWriter fw = new FileWriter(fout);
try-with-resources

2017-10-21 22:09 UTC, darkwrat commented
здесь что-то будет?

2017-10-27 09:10 UTC, darkwrat requested changes

2017-10-27 09:10 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +        TaskImplementation t = new TaskImplementation();
кажется тут лишнее)

2017-10-27 09:10 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +                FileInputStream fis = new FileInputStream(finPath);
стримы нужно обернуть в buffered, чтобы не уйти в 100% system cpu даже под небольшой нагрузкой

2017-10-27 09:10 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +            StringBuilder sb = new StringBuilder();
кажется это не используется. да и не нужно здесь в принципе

2017-10-27 09:10 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +            String toWrite;
конкатенировать строчку в цикле - плохая идея, мы об этом говорили на занятии 2
а давай сразу писать в выходной стрим?

2017-10-27 10:53 UTC, PeYceBall commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +                FileInputStream fis = new FileInputStream(finPath);
InputStream можно не оборачивать? Я ведь и так читаю по достаточно большому буферу

2017-11-08 09:57 UTC, darkwrat commented on L2-objects/src/main/java/ru/track/io/TaskImplementation.java
> +                FileInputStream fis = new FileInputStream(finPath);
буфер недостаточно большой, оптимальный размер - 4КБ или 8КБ. в логах чатика я кажется даже писал почему так )

2017-11-20 13:22 UTC, darkwrat commented
принято

2017-11-20 13:22 UTC, closed without merging